version: '3'

services:

  php:
    image: thecodingmachine/php:8.0-v4-fpm
    environment:
      # Disable extensions enabled by default
      # Enable extensions enabled by default
      PHP_EXTENSION_APCU: 1
      PHP_EXTENSION_REDIS: 1
      PHP_EXTENSION_ZIP: 1
      PHP_EXTENSION_OPCACHE: 1
      PHP_EXTENSION_GMP: 1
      # Enable needed extensions
      PHP_EXTENSION_MONGODB: 1
      PHP_EXTENSION_BCMATH: 1
      PHP_EXTENSION_IMAGICK: 1
      PHP_EXTENSION_SOCKETS: 1
      # XDebug configuration
      PHP_EXTENSION_XDEBUG: ${PHP_XDEBUG_INSTALL_EXTENSION}
      PHP_INI_XDEBUG__CLIENT_ENABLE: ${PHP_XDEBUG_REMOTE_ENABLE}
      PHP_INI_XDEBUG__CLIENT_AUTOSTART: ${PHP_XDEBUG_REMOTE_AUTOSTART}
      PHP_INI_XDEBUG__CLIENT_HOST: ${PHP_XDEBUG_REMOTE_HOST}
      PHP_INI_XDEBUG__CLIENT_PORT: ${PHP_XDEBUG_REMOTE_PORT}
      PHP_IDE_CONFIG: serverName=${PHP_IDE_CONFIG_SERVER_NAME}
    volumes:
    - .:/var/www/html:cached
    networks:
        - app-network

  nginx:
    image: nginx:stable
    depends_on:
    - php
    volumes:
    - .:/var/www/html:cached
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
